config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :usuarios

  resources :catalogo_homs

  resources :calz_hombres

  resources :cal_mujers

  resources :datos_del_clientes

  resources :carrito_de_compras

  resources :catalogos

  resources :colores

  resources :productos

  resources :colors

  resources :tallas

  resources :terminados

  resources :fichas

   root 'inicio#index'

end

app/models/carrito_de_compra.rb
class CarritoDeCompra < ActiveRecord::Base
end

app/models/catalogo.rb
class Catalogo < ActiveRecord::Base
end

app/models/catalogo_hom.rb
class CatalogoHom < ActiveRecord::Base
end

app/models/color.rb
class Color < ActiveRecord::Base
  belongs_to :nombre_color
end

app/models/datos_del_cliente.rb
class DatosDelCliente < ActiveRecord::Base
end

app/models/ficha.rb
class Ficha < ActiveRecord::Base
	
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :ficha
  belongs_to :talla
  belongs_to :color
  belongs_to :terminado
end

app/models/talla.rb
class Talla < ActiveRecord::Base
  belongs_to :medida
end

app/models/terminado.rb
class Terminado < ActiveRecord::Base
	belongs_to :bordado
end

app/controllers/datos_del_clientes_controller.rb
class DatosDelClientesController < ApplicationController
  before_action :set_datos_del_cliente, only: [:show, :edit, :update, :destroy]

  # GET /datos_del_clientes
  # GET /datos_del_clientes.json
  def index
    @datos_del_clientes = DatosDelCliente.all
  end

  # GET /datos_del_clientes/1
  # GET /datos_del_clientes/1.json
  def show
  end

  # GET /datos_del_clientes/new
  def new
    @datos_del_cliente = DatosDelCliente.new
  end

  # GET /datos_del_clientes/1/edit
  def edit
  end

  # POST /datos_del_clientes
  # POST /datos_del_clientes.json
  def create
    @datos_del_cliente = DatosDelCliente.new(datos_del_cliente_params)

    respond_to do |format|
      if @datos_del_cliente.save
        format.html { redirect_to @datos_del_cliente, notice: 'Datos del cliente was successfully created.' }
        format.json { render :show, status: :created, location: @datos_del_cliente }
      else
        format.html { render :new }
        format.json { render json: @datos_del_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datos_del_clientes/1
  # PATCH/PUT /datos_del_clientes/1.json
  def update
    respond_to do |format|
      if @datos_del_cliente.update(datos_del_cliente_params)
        format.html { redirect_to @datos_del_cliente, notice: 'Datos del cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @datos_del_cliente }
      else
        format.html { render :edit }
        format.json { render json: @datos_del_cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datos_del_clientes/1
  # DELETE /datos_del_clientes/1.json
  def destroy
    @datos_del_cliente.destroy
    respond_to do |format|
      format.html { redirect_to datos_del_clientes_url, notice: 'Datos del cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datos_del_cliente
      @datos_del_cliente = DatosDelCliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datos_del_cliente_params
      params.require(:datos_del_cliente).permit(:nombre, :cedula, :apellido, :telefono, :direccion, :email, :ciudad, :forma_de_pago)
    end
end

app/controllers/fichas_controller.rb
class FichasController < ApplicationController
  before_action :set_ficha, only: [:show, :edit, :update, :destroy]

  # GET /fichas
  # GET /fichas.json
  def index
    @fichas = Ficha.all
  end

  # GET /fichas/1
  # GET /fichas/1.json
  def show
  end

  # GET /fichas/new
  def new
    @ficha = Ficha.new
  end

  # GET /fichas/1/edit
  def edit
  end

  # POST /fichas
  # POST /fichas.json
  def create
    
    @ficha = Ficha.new(ficha_params)

    respond_to do |format|
      if @ficha.save
        format.html { redirect_to @ficha, notice: 'Ficha was successfully created.' }
        format.json { render :show, status: :created, location: @ficha }
      else
        format.html { render :new }
        format.json { render json: @ficha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fichas/1
  # PATCH/PUT /fichas/1.json
  def update
    respond_to do |format|
      if @ficha.update(ficha_params)
        format.html { redirect_to @ficha, notice: 'Ficha was successfully updated.' }
        format.json { render :show, status: :ok, location: @ficha }
      else
        format.html { render :edit }
        format.json { render json: @ficha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fichas/1
  # DELETE /fichas/1.json
  def destroy
    @ficha.destroy
    respond_to do |format|
      format.html { redirect_to fichas_url, notice: 'Ficha was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ficha
      @ficha = Ficha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ficha_params
      params.require(:ficha).permit(:nombre, :codigo)
    end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogo_homs_helper.rb
module CatalogoHomsHelper
end

app/helpers/catalogos_helper.rb
module CatalogosHelper
end

app/helpers/colores_helper.rb
module ColoresHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/datos_del_clientes_helper.rb
module DatosDelClientesHelper
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/tallas_helper.rb
module TallasHelper
end

app/helpers/terminados_helper.rb
module TerminadosHelper
end

app/views/datos_del_clientes/_form.html.erb
<%= simple_form_for @datos_del_cliente, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :nombre %>
  <%= f.input :cedula %>
  <%= f.input :apellido %>
  <%= f.input :telefono %>
  <%= f.input :direccion %>
  <%= f.input :email %>
  <%= f.input :ciudad %>
  <%= f.input :forma_de_pago %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                datos_del_clientes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/datos_del_clientes/edit.html.erb
<%- model_class = DatosDelCliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.Editar', 'Editar %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/datos_del_clientes/index.html.erb
<%- model_class = DatosDelCliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:cedula) %></th>
      <th><%= model_class.human_attribute_name(:apellido) %></th>
      <th><%= model_class.human_attribute_name(:telefono) %></th>
      <th><%= model_class.human_attribute_name(:direccion) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:ciudad) %></th>
      <th><%= model_class.human_attribute_name(:forma_de_pago) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @datos_del_clientes.each do |datos_del_cliente| %>
      <tr>
        <td><%= link_to datos_del_cliente.id, datos_del_cliente_path(datos_del_cliente) %></td>
        <td><%= datos_del_cliente.nombre %></td>
        <td><%= datos_del_cliente.cedula %></td>
        <td><%= datos_del_cliente.apellido %></td>
        <td><%= datos_del_cliente.telefono %></td>
        <td><%= datos_del_cliente.direccion %></td>
        <td><%= datos_del_cliente.email %></td>
        <td><%= datos_del_cliente.ciudad %></td>
        <td><%= datos_del_cliente.forma_de_pago %></td>
        <td><%=l datos_del_cliente.created_at %></td>
        <td>
          <%= link_to t('.Editar', :default => t("helpers.links.Editar")),
                      edit_datos_del_cliente_path(datos_del_cliente), :class => 'btn btn-mini' %>
          <%= link_to t('.Eliminar', :default => t("helpers.links.Eliminar")),
                      datos_del_cliente_path(datos_del_cliente),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Esta seguro?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.Nuevo', :default => t("helpers.links.Nuevo")),
            new_datos_del_cliente_path,
            :class => 'btn btn-primary' %>

app/views/datos_del_clientes/new.html.erb
<%- model_class = DatosDelCliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.Nuevo', 'Nuevo %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/datos_del_clientes/show.html.erb
<%- model_class = DatosDelCliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @datos_del_cliente.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cedula) %>:</strong></dt>
  <dd><%= @datos_del_cliente.cedula %></dd>
  <dt><strong><%= model_class.human_attribute_name(:apellido) %>:</strong></dt>
  <dd><%= @datos_del_cliente.apellido %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefono) %>:</strong></dt>
  <dd><%= @datos_del_cliente.telefono %></dd>
  <dt><strong><%= model_class.human_attribute_name(:direccion) %>:</strong></dt>
  <dd><%= @datos_del_cliente.direccion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @datos_del_cliente.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ciudad) %>:</strong></dt>
  <dd><%= @datos_del_cliente.ciudad %></dd>
  <dt><strong><%= model_class.human_attribute_name(:forma_de_pago) %>:</strong></dt>
  <dd><%= @datos_del_cliente.forma_de_pago %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.Atras', :default => t("helpers.links.Atras")),
              datos_del_clientes_path, :class => 'btn'  %>
  <%= link_to t('.Editar', :default => t("helpers.links.Editar")),
              edit_datos_del_cliente_path(@datos_del_cliente), :class => 'btn' %>
  <%= link_to t('.Eliminar', :default => t("helpers.links.Eliminar")),
              datos_del_cliente_path(@datos_del_cliente),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Esta seguro?')) },
              :class => 'btn btn-danger' %>
</div>