config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :usuarios

  resources :catalogo_homs

  resources :calz_hombres

  resources :cal_mujers

  resources :datos_del_clientes

  resources :carrito_de_compras

  resources :catalogos

  resources :colores

  resources :productos

  resources :colors

  resources :tallas

  resources :terminados

  resources :fichas

   root 'inicio#index'

end

app/models/carrito_de_compra.rb
class CarritoDeCompra < ActiveRecord::Base
end

app/models/catalogo.rb
class Catalogo < ActiveRecord::Base
end

app/models/catalogo_hom.rb
class CatalogoHom < ActiveRecord::Base
end

app/models/color.rb
class Color < ActiveRecord::Base
  belongs_to :nombre_color
end

app/models/datos_del_cliente.rb
class DatosDelCliente < ActiveRecord::Base
end

app/models/ficha.rb
class Ficha < ActiveRecord::Base
	
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :ficha
  belongs_to :talla
  belongs_to :color
  belongs_to :terminado
end

app/models/talla.rb
class Talla < ActiveRecord::Base
  belongs_to :medida
end

app/models/terminado.rb
class Terminado < ActiveRecord::Base
	belongs_to :bordado
end

app/controllers/colores_controller.rb
class ColoresController < ApplicationController
  before_action :set_color, only: [:show, :edit, :update, :destroy]

  # GET /colores
  # GET /colores.json
  def index
    @colores = Color.all
  end

  # GET /colores/1
  # GET /colores/1.json
  def show
  end

  # GET /colores/new
  def new
    @color = Color.new
  end

  # GET /colores/1/edit
  def edit
  end

  # POST /colores
  # POST /colores.json
  def create
    @color = Color.new(color_params)

    respond_to do |format|
      if @color.save
        format.html { redirect_to @color, notice: 'Color was successfully created.' }
        format.json { render :show, status: :created, location: @color }
      else
        format.html { render :new }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colores/1
  # PATCH/PUT /colores/1.json
  def update
    respond_to do |format|
      if @color.update(color_params)
        format.html { redirect_to @color, notice: 'Color was successfully updated.' }
        format.json { render :show, status: :ok, location: @color }
      else
        format.html { render :edit }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colores/1
  # DELETE /colores/1.json
  def destroy
    @color.destroy
    respond_to do |format|
      format.html { redirect_to colores_url, notice: 'Color was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color
      @color = Color.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def color_params
      params.require(:color).permit(:nombre, :codigo)
    end
end

app/controllers/fichas_controller.rb
class FichasController < ApplicationController
  before_action :set_ficha, only: [:show, :edit, :update, :destroy]

  # GET /fichas
  # GET /fichas.json
  def index
    @fichas = Ficha.all
  end

  # GET /fichas/1
  # GET /fichas/1.json
  def show
  end

  # GET /fichas/new
  def new
    @ficha = Ficha.new
  end

  # GET /fichas/1/edit
  def edit
  end

  # POST /fichas
  # POST /fichas.json
  def create
    
    @ficha = Ficha.new(ficha_params)

    respond_to do |format|
      if @ficha.save
        format.html { redirect_to @ficha, notice: 'Ficha was successfully created.' }
        format.json { render :show, status: :created, location: @ficha }
      else
        format.html { render :new }
        format.json { render json: @ficha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fichas/1
  # PATCH/PUT /fichas/1.json
  def update
    respond_to do |format|
      if @ficha.update(ficha_params)
        format.html { redirect_to @ficha, notice: 'Ficha was successfully updated.' }
        format.json { render :show, status: :ok, location: @ficha }
      else
        format.html { render :edit }
        format.json { render json: @ficha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fichas/1
  # DELETE /fichas/1.json
  def destroy
    @ficha.destroy
    respond_to do |format|
      format.html { redirect_to fichas_url, notice: 'Ficha was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ficha
      @ficha = Ficha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ficha_params
      params.require(:ficha).permit(:nombre, :codigo)
    end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
	def index
	end
end

app/controllers/tallas_controller.rb
class TallasController < ApplicationController
  before_action :set_talla, only: [:show, :edit, :update, :destroy]

  # GET /tallas
  # GET /tallas.json
  def index
    @tallas = Talla.all
  end

  # GET /tallas/1
  # GET /tallas/1.json
  def show
  end

  # GET /tallas/new
  def new
    @talla = Talla.new
  end

  # GET /tallas/1/edit
  def edit
  end

  # POST /tallas
  # POST /tallas.json
  def create
    @talla = Talla.new(talla_params)

    respond_to do |format|
      if @talla.save
        format.html { redirect_to @talla, notice: 'Talla was successfully created.' }
        format.json { render :show, status: :created, location: @talla }
      else
        format.html { render :new }
        format.json { render json: @talla.errors, status: :unprocessable_entity }
      end
    end
  end
 end
  # PATCH/PUT /tallas/1
  # PATCH/PUT /tallas/1.json
  def update
    respond_to do |format|
      if @talla.update(talla_params)
        format.html { redirect_to @talla, notice: 'Talla was successfully updated.' }
        format.json { render :show, status: :ok, location: @talla }
      else
        format.html { render :edit }
        format.json { render json: @talla.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tallas/1
  # DELETE /tallas/1.json
  def destroy
    @talla.destroy
    respond_to do |format|
      format.html { redirect_to tallas_url, notice: 'Talla was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_talla
      @talla = Talla.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def talla_params
      params.require(:talla).permit(:medida_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogo_homs_helper.rb
module CatalogoHomsHelper
end

app/helpers/catalogos_helper.rb
module CatalogosHelper
end

app/helpers/colores_helper.rb
module ColoresHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/tallas_helper.rb
module TallasHelper
end

app/helpers/terminados_helper.rb
module TerminadosHelper
end

app/views/fichas/_form.html.erb
<%= simple_form_for @ficha, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :nombre %>
  <%= f.input :codigo %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                fichas_path, :class => 'btn' %>
  </div>
<% end %>

app/views/fichas/edit.html.erb
<%- model_class = Ficha -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.Editar', 'Editar %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fichas/index.html.erb
<%- model_class = Ficha -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:codigo) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @fichas.each do |ficha| %>
      <tr>
        <td><%= link_to ficha.id, ficha_path(ficha) %></td>
        <td><%= ficha.nombre %></td>
        <td><%= ficha.codigo %></td>
        <td><%=l ficha.created_at %></td>
        <td>
          <%= link_to t('.Editar', :default => t("helpers.links.Editar")),
                      edit_ficha_path(ficha), :class => 'btn btn-mini' %>
          <%= link_to t('.Eliminar', :default => t("helpers.links.Eliminar")),
                      ficha_path(ficha),
                      :method => :delete,
                      :data => { :confirm => t('.Esta seguro', :default => t("helpers.links.confirm", :default => 'Esta seguro?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.Nuevo', :default => t("helpers.links.Nuevo")),
            new_ficha_path,
            :class => 'btn btn-primary' %>

app/views/fichas/new.html.erb
<%- model_class = Ficha -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.Nuevo', 'Nuevo %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fichas/show.html.erb
<%- model_class = Ficha -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @ficha.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:codigo) %>:</strong></dt>
  <dd><%= @ficha.codigo %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.Atras', :default => t("helpers.links.Atras")),
              fichas_path, :class => 'btn'  %>
  <%= link_to t('.Editar', :default => t("helpers.links.Editar")),
              edit_ficha_path(@ficha), :class => 'btn' %>
  <%= link_to t('.Eliminar', :default => t("helpers.links.Eliminar")),
              ficha_path(@ficha),
              :method => 'delete',
              :data => { :confirm => t('.Esta seguro', :default => t("helpers.links.confirm", :default => 'Esta seguro?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/tallas/_form.html.erb
<%= simple_form_for @talla, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :medida_id %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tallas_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tallas/edit.html.erb
<%- model_class = Talla -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.Editar', 'Editar %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tallas/index.html.erb
<%- model_class = Talla -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:medida_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tallas.each do |talla| %>
      <tr>
        <td><%= link_to talla.id, talla_path(talla) %></td>
        <td><%= talla.medida_id %></td>
        <td><%=l talla.created_at %></td>
        <td>
          <%= link_to t('.Editar', :default => t("helpers.links.Editar")),
                      edit_talla_path(talla), :class => 'btn btn-mini' %>
          <%= link_to t('.Eliminar', :default => t("helpers.links.Eliminar")),
                      talla_path(talla),
                      :method => :delete,
                      :data => { :confirm => t('.Esta seguro', :default => t("helpers.links.Esta seguro", :default => 'Esta seguro?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.Nuevo', :default => t("helpers.links.Nuevo")),
            new_talla_path,
            :class => 'btn btn-primary' %>

app/views/tallas/new.html.erb
<%- model_class = Talla -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.Nuevo', 'Nuevo %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tallas/show.html.erb
<%- model_class = Talla -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:medida_id) %>:</strong></dt>
  <dd><%= @talla.medida_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.Atras', :default => t("helpers.links.Atras")),
              tallas_path, :class => 'btn'  %>
  <%= link_to t('.Editar', :default => t("helpers.links.Editar")),
              edit_talla_path(@talla), :class => 'btn' %>
  <%= link_to t('.Eliminar', :default => t("helpers.links.Eliminar")),
              talla_path(@talla),
              :method => 'delete',
              :data => { :confirm => t('.Esta seguro', :default => t("helpers.links.Esta seguro", :default => 'Esta seguro?')) },
              :class => 'btn btn-danger' %>
</div>