config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :usuarios

  resources :catalogo_homs

  resources :calz_hombres

  resources :cal_mujers

  resources :datos_del_clientes

  resources :carrito_de_compras

  resources :catalogos

  resources :colores

  resources :productos

  resources :colors

  resources :tallas

  resources :terminados

  resources :fichas

   root 'inicio#index'

end

app/models/carrito_de_compra.rb
class CarritoDeCompra < ActiveRecord::Base
end

app/models/catalogo.rb
class Catalogo < ActiveRecord::Base
end

app/models/catalogo_hom.rb
class CatalogoHom < ActiveRecord::Base
end

app/models/color.rb
class Color < ActiveRecord::Base
  belongs_to :nombre_color
end

app/models/datos_del_cliente.rb
class DatosDelCliente < ActiveRecord::Base
end

app/models/ficha.rb
class Ficha < ActiveRecord::Base
	
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :ficha
  belongs_to :talla
  belongs_to :color
  belongs_to :terminado
end

app/models/talla.rb
class Talla < ActiveRecord::Base
  belongs_to :medida
end

app/models/terminado.rb
class Terminado < ActiveRecord::Base
	belongs_to :bordado
end

app/controllers/fichas_controller.rb
class FichasController < ApplicationController
  before_action :set_ficha, only: [:show, :edit, :update, :destroy]

  # GET /fichas
  # GET /fichas.json
  def index
    @fichas = Ficha.all
  end

  # GET /fichas/1
  # GET /fichas/1.json
  def show
  end

  # GET /fichas/new
  def new
    @ficha = Ficha.new
  end

  # GET /fichas/1/edit
  def edit
  end

  # POST /fichas
  # POST /fichas.json
  def create
    
    @ficha = Ficha.new(ficha_params)

    respond_to do |format|
      if @ficha.save
        format.html { redirect_to @ficha, notice: 'Ficha was successfully created.' }
        format.json { render :show, status: :created, location: @ficha }
      else
        format.html { render :new }
        format.json { render json: @ficha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fichas/1
  # PATCH/PUT /fichas/1.json
  def update
    respond_to do |format|
      if @ficha.update(ficha_params)
        format.html { redirect_to @ficha, notice: 'Ficha was successfully updated.' }
        format.json { render :show, status: :ok, location: @ficha }
      else
        format.html { render :edit }
        format.json { render json: @ficha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fichas/1
  # DELETE /fichas/1.json
  def destroy
    @ficha.destroy
    respond_to do |format|
      format.html { redirect_to fichas_url, notice: 'Ficha was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ficha
      @ficha = Ficha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ficha_params
      params.require(:ficha).permit(:nombre, :codigo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogo_homs_helper.rb
module CatalogoHomsHelper
end

app/helpers/catalogos_helper.rb
module CatalogosHelper
end

app/helpers/colores_helper.rb
module ColoresHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/fichas_helper.rb
module FichasHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/tallas_helper.rb
module TallasHelper
end

app/helpers/terminados_helper.rb
module TerminadosHelper
end

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">SHOES FOR ALL</a>
  </div>
  <div class="navbar-collapse collapse navbar-inverse-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "PRODUCTOS", productos_path %></li>
      <li><%= link_to "HOMBRES", catalogo_homs_path %></li>
      <li><%= link_to "MUJERES", catalogos_path %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">PROMOCIONES <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">30 %</a></li>
          <li><a href="#">50 %</a></li>
        </ul>
      </li>
    </ul>
  </div>

</div>

app/views/layouts/_navigation_links.html.erb
<% if currrent_user %>
<%=link_to "Edit profile", edit_user_path(currrent_user.id) %>
<%=link_to "logout", :logout, method: :get %>
<% else %>
<%=link_to "Register", new_user_path %> |
<%=link_to "Login", :login %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>PrendasVestir</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<header><%= render "layouts/navigation" %></header>
<div class="container">
 
<div class="row">
	<%= yield %>

</div>

</div>

</body>
</html>